[package]
name = "historic_sys"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
bcrypt = "0.15.1"
dotenv = "0.15.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-async-std"] }
