name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_URL: "postgresql://localhost:5432?dbname=r_test&user=postgres&password=1234"
  JSON_WEB_TOKEN_SECRET: ${{ secrets.JSON_WEB_TOKEN_SECRET }}
  FRONTEND_DOMAIN: "http://localhost:3000"
  GPT_URL: ${{ secrets.GPT_URL }}
  GPT_KEY: ${{ secrets.GPT_KEY }}
  GPT_ASSISTENT: ${{ secrets.GPT_ASSISTENT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
